name: carteras
description: Sistema de gestión de préstamos y cobranza
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Estado
  provider: ^6.1.2
  
  # Base de datos
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0
  
  # Imágenes
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  
  # Utilidades
  intl: ^0.19.0
  
  # PDF
  pdf: ^3.11.1
  printing: ^5.13.1
  
  # Compartir
  share_plus: ^9.0.0
  
  # Conectividad
  connectivity_plus: ^6.0.3
  
  # URL launcher (para llamadas)
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
 # assets:
 #   - assets/images/
